### PR TITLE
Authors modal padding fix

### PR DESCRIPTION
**Pull request by ErnestaP**

### CODE REVIEW

**Review by karolina-siemieniuk-morawska — CHANGES_REQUESTED** [review]
This will result in increasing the padding in title bar as well as in modal body, and this is not the desired result 
Screenshot 2024-03-04 at 11 12 21


This is what we want
Screenshot 2024-03-04 at 11 13 46

**Review by karolina-siemieniuk-morawska — CHANGES_REQUESTED** [review]
Now the title and content will be misaligned
 
Screenshot 2024-03-04 at 11 17 54

I'd suggest changing https://github.com/SCOAP3/scoap3/blob/b627d2387801b1cb578f7074d3ab3677b018bad5/ui/src/styles/globals.css#L520 to ```div.ant-modal .ant-modal-body```

**Comment by ErnestaP** [comment]
The results of changes:
Screenshot 2024-03-04 at 11 23 14

**Comment by ErnestaP** [comment]
Screenshot 2024-03-04 at 11 33 30

with equal paddings

**Review by karolina-siemieniuk-morawska — APPROVED** [review]

**Comment by ErnestaP** [comment]
Screenshot-2024-03-04-at-11 39 29
final result

**Pull request merged**
